version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    tty: true
    environment:
      MYSQL_HOST: auth-db-container
      MYSQL_PORT: 3306
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MASQL_DATABASE: user
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: passw0rd
    ports:
      - 8888:8080
    depends_on:
      - db
    networks:
      - auth_network
      - auth_db

  db:
    image: mysql:8.0
    tty: true
    container_name: auth-db-container
    hostname: auth-db-server
    ports:
      - 3333:3306
    volumes:
      - type: volume
        source: auth_user_volume
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MASQL_DATABASE: auth
      MYSQL_PASSWORD: passw0rd
      MYSQL_USER: auth_user
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - auth_db

networks:
  auth_network:
    name: auth_network
    driver: bridge
    external: true
  auth_db:
    name: auth_db
    driver: bridge
    external: true

volumes:
  auth_user_volume:
    name: auth_user_volume
    external: true